# Generated by Django 5.2 on 2025-04-18 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_created_at_subscription_subscribed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscribed_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
