# Generated by Django 5.2 on 2025-04-18 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_mealplan_dailymenu_subscription_meal_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_subscriptions', to='users.vendorprofile'),
        ),
    ]
