# Generated by Django 5.2 on 2025-04-18 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meals', to='users.vendorprofile'),
        ),
    ]
