# Generated by Django 5.2 on 2025-04-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_meal_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meal_plan_images/'),
        ),
    ]
