# Generated by Django 5.2 on 2025-04-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Paid', 'Paid'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
