# Generated by Django 5.2 on 2025-04-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_notification_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='business_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
